name: track_me
description: A Flutter app
version: 0.7.0+14
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  awesome_notifications: 0.10.1
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: 3.0.3
  freezed_annotation: 3.1.0
  go_router: 17.0.1
  google_fonts: 6.3.3
  hive_ce: 2.16.0
  hive_ce_flutter: 2.3.3
  intl: 0.20.2
  json_annotation: 4.9.0
  path_provider: 2.1.5
  riverpod_annotation: 3.0.3
  shared_preferences: 2.5.4
  uuid: 4.5.2

dev_dependencies:
  build_runner: 2.10.4
  custom_lint: 0.8.1
  freezed: 3.2.3
  hive_ce_generator: 1.10.0
  json_serializable: 6.11.2
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3
  very_good_analysis: 10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Icons
    - assets/icons/

    # Images
    - assets/images/
